name: Build docker image
on: [ push ]

env:
  ACTIONS_PYTHON_VERSION: '3.10'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          cache-from: |
            type=registry,ref=ghcr.io/ualbertaaltlab/wordnet-docker:latest
          tags: |
            ghcr.io/ualbertaaltlab/wordnet-docker:${{ github.sha }}
            ghcr.io/ualbertaaltlab/wordnet-docker:latest

